const API_BASE=(window.HJ_API_BASE||`${location.origin}/api`).replace(/\/$/,'');
const TOKEN_KEY='HJ_EARNING_TOKEN_V1';
const AUTH_KEY='HJ_EARNING_AUTH_V1';
const token=()=>localStorage.getItem(TOKEN_KEY)||'';
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function getAuth(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch{return null}}
function setSession(d){localStorage.setItem(TOKEN_KEY,d.token);localStorage.setItem(AUTH_KEY,JSON.stringify(d.user))}
function clearSession(){localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(AUTH_KEY)}
async function api(path,opt={}){opt.headers={...(opt.headers||{}),'Content-Type':'application/json'};const t=token();if(t)opt.headers.Authorization='Bearer '+t;const r=await fetch(API_BASE+path,{...opt,cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
function showLogin(message=''){document.getElementById('adminLogin').style.display='flex';document.getElementById('adminApp').style.display='none';if(message)document.getElementById('loginMsg').textContent=message;}
function showApp(){document.getElementById('adminLogin').style.display='none';document.getElementById('adminApp').style.display='block';load()}
async function verifyAdmin(){const u=getAuth();if(!token()){showLogin();return}try{const d=await api('/admin/stats');if(d&&typeof d.users!=='undefined'){showApp();return}}catch(e){}clearSession();showLogin('Please login with an admin account.');}
async function adminLogin(){const email=document.getElementById('adminEmail').value.trim(),password=document.getElementById('adminPassword').value;if(!email||!password)return document.getElementById('loginMsg').textContent='Enter admin email and password.';document.getElementById('loginBtn').disabled=true;try{const d=await api('/auth/admin-login',{method:'POST',body:JSON.stringify({email,password})});if(d.user?.role!=='admin'){clearSession();throw new Error('This account is not an admin account.')}setSession(d);showApp()}catch(e){clearSession();document.getElementById('loginMsg').textContent=e.message}finally{document.getElementById('loginBtn').disabled=false}}
function hjLogout(){clearSession();showLogin('Logged out successfully.');document.getElementById('adminPassword').value=''}
async function load(){try{const results=await Promise.allSettled([api('/admin/withdrawals'),api('/admin/stats'),api('/admin/users'),api('/admin/redeem-codes')]);const [rd,rs,ru,rc]=results;if(results.some(x=>x.status==='rejected'&&String(x.reason?.message||'').toLowerCase().includes('token'))){return showLogin('Admin session expired. Please login again.')}const d=rd.status==='fulfilled'?rd.value:{withdrawals:[]};const st=rs.status==='fulfilled'?rs.value:{users:0,pending:0,approved:0,rejected:0};const u=ru.status==='fulfilled'?ru.value:{users:[]};const c=rc.status==='fulfilled'?rc.value:{codes:[]};document.querySelector('#adminMsg').textContent=`${u.users.length} account(s) • ${d.withdrawals.length} withdrawal(s) • ${st.pending} pending`;document.querySelector('#adminStats').innerHTML=`<div class="stat"><b>${st.users}</b><span>Users</span></div><div class="stat"><b>${st.pending}</b><span>Pending</span></div><div class="stat"><b>${st.approved}</b><span>Complete</span></div><div class="stat"><b>${st.rejected}</b><span>Rejected</span></div>`;
document.querySelector('#adminTable tbody').innerHTML=d.withdrawals.map(w=>`<tr><td>#${w.id}</td><td>${esc(w.name)}<br><small>${esc(w.email)}</small></td><td>${esc(w.method)}</td><td>${esc(w.accountNumber)}</td><td>${Number(w.points).toLocaleString()}</td><td>Rs ${esc(w.rupees)}</td><td><span class="status-pill ${w.status==='Complete'?'status-complete':w.status==='Rejected'?'status-rejected':'status-pending'}">${w.status}</span>${w.adminNote?`<br><small>${esc(w.adminNote)}</small>`:''}</td><td>${w.status==='Pending'?`<button class="success-btn" onclick="act(${w.id},'complete')">Complete</button> <button class="danger-btn" onclick="act(${w.id},'reject')">Reject</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="8">No withdrawal requests.</td></tr>';
document.querySelector('#usersTable tbody').innerHTML=u.users.map(x=>`<tr><td>#${x.id}</td><td>${esc(x.name)}<br><small>${esc(x.email)}</small></td><td><span class="status-pill ${x.role==='admin'?'status-complete':'status-pending'}">${esc(x.role)}</span></td><td>${esc(x.referralCode||'—')}</td><td>${Number(x.points).toLocaleString()}</td><td>${x.role==='admin'?'<span class="muted">Admin account</span>':`<button onclick="editPoints(${x.id},${Number(x.points)},'${esc(x.name)}')">Edit Points</button>`}</td></tr>`).join('')||'<tr><td colspan="6">No registered accounts found.</td></tr>';
document.querySelector('#codesTable tbody').innerHTML=c.codes.map(x=>`<tr><td><b>${esc(x.code)}</b></td><td>${Number(x.points).toLocaleString()}</td><td>${x.usedCount}/${x.maxUses}</td><td>${x.expiresAt?new Date(x.expiresAt).toLocaleString():'Never'}</td><td>${x.active?'Active':'Disabled'}</td><td><button onclick="toggleCode(${x.id},${!x.active})">${x.active?'Disable':'Enable'}</button></td></tr>`).join('')||'<tr><td colspan="6">No redeem codes.</td></tr>';
}catch(e){document.querySelector('#adminMsg').textContent=e.message}}
async function act(id,action){const note=prompt(action==='complete'?'Admin note (optional)':'Reason for rejection (optional)');if(note===null)return;try{await api('/admin/withdrawals/'+id,{method:'PATCH',body:JSON.stringify({action,note})});await load()}catch(e){alert(e.message)}}
async function editPoints(id,current,name){const raw=prompt(`Points adjustment for ${name}.\nCurrent balance: ${current}\nUse +500 or -500.`, '');if(raw===null)return;const amount=Number(raw);if(!Number.isInteger(amount)||amount===0)return alert('Enter a non-zero whole number.');const description=prompt('Reason/note (optional):','Admin points adjustment');if(description===null)return;try{await api('/admin/users/'+id+'/points',{method:'PATCH',body:JSON.stringify({amount,description})});await load();alert('Points updated successfully.')}catch(e){alert(e.message)}}
async function createCode(){const code=document.getElementById('newCode').value.trim(),points=Number(document.getElementById('codePoints').value),maxUses=Number(document.getElementById('codeUses').value||1),expiresAt=document.getElementById('codeExpiry').value?new Date(document.getElementById('codeExpiry').value).toISOString().slice(0,19).replace('T',' '):null;if(!Number.isInteger(points)||points<=0)return alert('Enter valid points.');try{const d=await api('/admin/redeem-codes',{method:'POST',body:JSON.stringify({code,points,maxUses,expiresAt})});document.getElementById('newCode').value='';document.getElementById('codePoints').value='';alert('Code created: '+d.code);await load()}catch(e){alert(e.message)}}
async function toggleCode(id,active){try{await api('/admin/redeem-codes/'+id,{method:'PATCH',body:JSON.stringify({active})});await load()}catch(e){alert(e.message)}}
window.adminLogin=adminLogin;window.hjLogout=hjLogout;window.act=act;window.editPoints=editPoints;window.createCode=createCode;window.toggleCode=toggleCode;window.load=load;document.addEventListener('DOMContentLoaded',verifyAdmin);
